import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { chmod, copyFile, mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, join } from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import z from "schemastery";
/** Default GUI URL. */
const DEFAULT_URL = "http://127.0.0.1:3080";
/** Resolve defaults from a partial config; empty profile means "no --profile flag". */
function resolveLauncherSpec(config) {
	return {
		dshCommand: config.dshCommand ?? "dsh",
		url: config.url ?? "http://127.0.0.1:3080",
		...config.profile === void 0 || config.profile === "" ? {} : { profile: config.profile },
		...config.iconPath === void 0 || config.iconPath === "" ? {} : { iconPath: config.iconPath }
	};
}
/** File name of the launcher script under <dsh-home>/desktop-quick-launcher/. */
function scriptFileName(platform) {
	switch (platform) {
		case "win32": return "launcher.ps1";
		case "darwin": return "launcher.command";
		case "linux": return "launcher.sh";
	}
}
/** File name of the icon placed on the Desktop. */
function desktopFileName(platform) {
	switch (platform) {
		case "win32": return "DSH-Web.lnk";
		case "darwin": return "DeepSeek-Harness.command";
		case "linux": return "deepseek-harness.desktop";
	}
}
/** Single-quote a value for PowerShell (embedded quotes are doubled). */
function psSingle(value) {
	return `'${value.replaceAll("'", "''")}'`;
}
/** Single-quote a value for POSIX sh (embedded quotes are escaped). */
function shSingle(value) {
	return `'${value.replaceAll("'", "'\\''")}'`;
}
/**
* PowerShell launcher body: probes the URL, starts `dsh web --no-open`
* hidden, polls until the GUI answers, then opens the default browser. Every
* branch writes to launcher.log next to the script (invoked / found dsh /
* spawned pid / child exit / ready / each open attempt / timeout) so a
* "does not auto-open" report can be diagnosed from the log. Browser opening
* tries Start-Process, then explorer.exe, then `cmd /c start`.
*/
function renderPowerShell(spec) {
	return [
		"# DSH web launcher (generated by dsh-desktop_quick_launcher)",
		"$ErrorActionPreference = 'Continue'",
		`$dshCommand = ${psSingle(spec.dshCommand)}`,
		`$url = ${psSingle(spec.url)}`,
		`$profile = ${psSingle(spec.profile ?? "")}`,
		"$log = Join-Path $PSScriptRoot 'launcher.log'",
		"",
		"function Write-Log($message) {",
		"  try { Add-Content -Path $log -Value (('[dsh-launcher] ' + (Get-Date -Format 's') + ' | ' + $message)) } catch {}",
		"}",
		"",
		"function Test-DshUrl {",
		"  try {",
		"    $r = Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 2",
		"    return $r.StatusCode -ge 200 -and $r.StatusCode -lt 500",
		"  } catch {",
		"    if ($_.Exception.Response -and $_.Exception.Response.StatusCode) {",
		"      $code = [int]$_.Exception.Response.StatusCode",
		"      return $code -ge 200 -and $code -lt 500",
		"    }",
		"    return $false",
		"  }",
		"}",
		"",
		"function Open-Browser {",
		"  $opened = $false",
		"  try { Start-Process -FilePath $url -ErrorAction Stop; $opened = $true } catch { Write-Log ('Start-Process open failed: ' + $_) }",
		"  if (-not $opened) { try { Start-Process -FilePath 'explorer.exe' -ArgumentList $url -ErrorAction Stop; $opened = $true } catch { Write-Log ('explorer open failed: ' + $_) } }",
		"  if (-not $opened) { try { cmd.exe /c start '' $url 2>&1 | Out-Null; $opened = $true } catch { Write-Log ('cmd start open failed: ' + $_) } }",
		"  Write-Log ('open-browser result: opened=' + $opened)",
		"}",
		"",
		"function Show-Message($text, $title) {",
		"  try {",
		"    Add-Type -AssemblyName PresentationFramework -ErrorAction Stop | Out-Null",
		"    [System.Windows.MessageBox]::Show($text, $title) | Out-Null",
		"  } catch { Write-Log (\"message box failed: \" + $_) }",
		"}",
		"",
		"Write-Log 'launcher invoked'",
		"if (Test-DshUrl) {",
		"  Write-Log ('already running -> open ' + $url)",
		"  Open-Browser",
		"  exit 0",
		"}",
		"",
		"$commands = @(Get-Command $dshCommand -All -ErrorAction SilentlyContinue)",
		"$command = $commands | Where-Object { $_.CommandType -eq 'Application' -and $_.Source -match '\\.(?:cmd|exe|bat|com)$' } | Select-Object -First 1",
		"if ($null -eq $command) { $command = $commands | Where-Object { $_.CommandType -eq 'Application' } | Select-Object -First 1 }",
		"if ($null -eq $command) { $command = $commands | Where-Object { $_.CommandType -eq 'ExternalScript' } | Select-Object -First 1 }",
		"if ($null -eq $command) {",
		"  Write-Log ('dsh command not found: ' + $dshCommand)",
		"  Show-Message (\"找不到 dsh 命令：\" + $dshCommand) \"DSH Quick Launcher\"",
		"  exit 1",
		"}",
		"",
		"Write-Log ('found dsh: ' + $command.Source)",
		"$arguments = if ($profile -eq \"\") { @(\"web\", \"--no-open\") } else { @(\"--profile\", $profile, \"--no-open\") }",
		"if ($command.CommandType -eq \"ExternalScript\" -or $command.Source -match \"\\.ps1$\") {",
		"  $arguments = @(\"-NoProfile\", \"-File\", $command.Source) + $arguments",
		"  $dshProcess = Start-Process -FilePath \"powershell.exe\" -ArgumentList $arguments -WindowStyle Hidden -PassThru",
		"} else {",
		"  $dshProcess = Start-Process -FilePath $command.Source -ArgumentList $arguments -WindowStyle Hidden -PassThru",
		"}",
		"Write-Log ('spawned dsh, pid=' + $dshProcess.Id)",
		"",
		"$deadline = (Get-Date).AddSeconds(150)",
		"$ready = $false",
		"while ((Get-Date) -lt $deadline) {",
		"  Start-Sleep -Milliseconds 500",
		"  if (Test-DshUrl) { $ready = $true; break }",
		"  if ($null -ne $dshProcess -and $dshProcess.HasExited) {",
		"    Write-Log ('dsh process exited early, code=' + $dshProcess.ExitCode)",
		"    Show-Message ('DSH 进程启动后退出（代码：' + $dshProcess.ExitCode + '）。' + [char]10 + '若 3080 端口已被其他实例占用，请先停止旧实例再双击启动。' + [char]10 + '日志：' + $log) 'DSH Quick Launcher'",
		"    exit 1",
		"  }",
		"}",
		"if ($ready) {",
		"  Write-Log 'service ready -> open browser'",
		"  Open-Browser",
		"  exit 0",
		"}",
		"Write-Log ('timeout: not ready within 150s, url=' + $url)",
		"Show-Message ('150 秒内未就绪：' + $url + [char]10 + '服务若仍在后台启动，可稍后手动访问该地址。' + [char]10 + '日志：' + $log) 'DSH Quick Launcher'",
		"exit 1",
		""
	].join("\n");
}
/** POSIX launcher (macOS .command / Linux .sh) with the platform open command. */
function renderPosix(platform, spec) {
	const open = platform === "darwin" ? "open" : "xdg-open";
	const alert = platform === "darwin" ? "osascript -e 'display dialog \"dsh command not found: '\"$DASH\"'\" with title \"DSH Quick Launcher\" with icon caution' 2>/dev/null || echo \"dsh command not found: $DASH\" >&2" : "zenity --error --title=\"DSH Quick Launcher\" --text=\"dsh command not found: $DASH\" 2>/dev/null || echo \"dsh command not found: $DASH\" >&2";
	return [
		"#!/bin/bash",
		"# DSH web launcher (generated by dsh-desktop_quick_launcher)",
		`DASH=${shSingle(spec.dshCommand)}`,
		`URL=${shSingle(spec.url)}`,
		`PROFILE=${shSingle(spec.profile ?? "")}`,
		"",
		"probe() {",
		"  curl -fsS --max-time 2 \"$URL\" >/dev/null 2>&1",
		"}",
		"",
		"if probe; then",
		`  ${open} "$URL"`,
		"  exit 0",
		"fi",
		"",
		"if ! command -v \"$DASH\" >/dev/null 2>&1; then",
		`  ${alert}`,
		"  exit 1",
		"fi",
		"",
		"if [ -n \"$PROFILE\" ]; then",
		"  \"$DASH\" --profile \"$PROFILE\" --no-open >/dev/null 2>&1 &",
		"else",
		"  \"$DASH\" web --no-open >/dev/null 2>&1 &",
		"fi",
		"DASH_PID=$!",
		"",
		"for i in $(seq 1 60); do",
		"  if probe; then",
		`    ${open} "$URL"`,
		"    exit 0",
		"  fi",
		"  if ! kill -0 \"$DASH_PID\" 2>/dev/null; then",
		"    echo \"dsh process exited unexpectedly\" >&2",
		"    exit 1",
		"  fi",
		"  sleep 2",
		"done",
		"",
		"echo \"dsh web did not start within 120 seconds: $URL\" >&2",
		"exit 1",
		""
	].join("\n");
}
/** Render the launcher script for one platform. */
function renderLauncherScript(platform, spec) {
	switch (platform) {
		case "win32": return renderPowerShell(spec);
		case "darwin":
		case "linux": return renderPosix(platform, spec);
	}
}
/** Render the Linux desktop entry (macOS uses the launcher itself as the desktop file). */
function renderDesktopEntry(launcherPath, iconPath) {
	const iconLine = iconPath === void 0 ? "Icon=utilities-terminal" : `Icon=${iconPath}`;
	return [
		"[Desktop Entry]",
		"Type=Application",
		"Version=1.0",
		"Name=DSH Web",
		"Comment=Launch DeepSeek Harness Web GUI",
		`Exec="${launcherPath}"`,
		iconLine,
		"Terminal=true",
		"Categories=Development;",
		""
	].join("\n");
}
/**
* Render the Windows shortcut installer: a PowerShell script that creates the
* Desktop .lnk pointing at the launcher script, executed hidden by the host.
*/
function renderShortcutInstaller(opts) {
	const { launcherPath, desktopPath, workingDirectory, iconLocation } = opts;
	const targetWorkingDir = workingDirectory ?? "";
	return [
		"# DSH desktop shortcut installer (generated by dsh-desktop_quick_launcher)",
		"$ErrorActionPreference = 'Stop'",
		"$ws = New-Object -ComObject WScript.Shell",
		`$shortcut = $ws.CreateShortcut(${psSingle(desktopPath)})`,
		`$shortcut.TargetPath = ${psSingle("powershell.exe")}`,
		`$shortcut.Arguments = ${psSingle(`-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ${launcherPath}`)}`,
		`$shortcut.WorkingDirectory = ${psSingle(targetWorkingDir)}`,
		`$shortcut.IconLocation = ${psSingle(iconLocation)}`,
		`$shortcut.Description = ${psSingle("Launch DeepSeek Harness Web GUI")}`,
		"$shortcut.Save()",
		""
	].join("\n");
}
//#endregion
//#region src/index.ts
/**
* dsh-desktop_quick_launcher — host half.
*
* Migrated core logic from the retired @linxin666/dsh-desktop-launcher
* (Apache-2.0): serves a loopback-only API family under
* /api/dsh-desktop_quick_launcher:
*   - POST /create   writes the launcher script under <dsh-home>/
*                    desktop-quick-launcher/ and places a double-click icon on
*                    the Desktop (Windows .lnk / macOS .command / Linux
*                    .desktop);
*   - POST /shutdown asks the host process to exit gracefully (ctx.appExit,
*                    process.exit(0) fallback) after the response is flushed.
*
* It also owns a schemastery settings section (`desktop-quick-launcher`
* namespace, edited from Settings) and an optional system-prompt section. The
* browser half (./client) renders a floating power button that triggers both
* routes. Everything rides the official DSH SDK packages; no dsh source
* changes.
*/
const execFileAsync = promisify(execFile);
/** Stable cordis plugin name. */
const name = "dsh-desktop_quick_launcher";
/** Host services this plugin consumes. */
const inject = ["webServer", "systemPrompt"];
/** Wire contract between host routes and the browser API helpers. */
const LAUNCHER_API = {
	/** Create (or refresh) the desktop icon. */
	create: "/api/dsh-desktop_quick_launcher/create",
	/** Request the host process to exit gracefully. */
	shutdown: "/api/dsh-desktop_quick_launcher/shutdown"
};
const Config = z.object({
	enabled: z.boolean().default(true),
	announceToAgent: z.boolean().default(false),
	dshCommand: z.string().default("dsh"),
	url: z.string().default(DEFAULT_URL),
	profile: z.string().default(""),
	iconPath: z.string().default(""),
	confirmShutdown: z.boolean().default(true)
});
/** Settings namespace owned by this plugin (host + browser spell the same value). */
const NAMESPACE = "desktop-quick-launcher";
/** Order of the announcement section within the tool-guidance band. */
const SECTION_ORDER = 210;
const DESKTOP_QUICK_LAUNCHER_GUIDANCE = "本机已安装 desktop-quick-launcher 插件（DSH 桌面快捷启动 + 一键退出）：「设置 → 插件配置」可配置 dshCommand / url / profile；界面右下角悬浮面板可一键「生成/刷新桌面图标」（Windows .lnk 双击即启动 dsh web 并打开浏览器）或「停止 DSH 服务」（确认后请求宿主进程优雅退出）。限制：图标创建与退出接口均仅限本机回环访问；退出会终止 dsh web 进程，正在运行的会话/任务可能中断。用户提到「桌面图标 / 快捷方式 / 一键启动 / 退出 DSH」时即指本插件。";
function isIPv4Loopback(v4) {
	const parts = v4.split(".");
	return parts.length === 4 && parts[0] === "127" && parts.every((part) => /^\d{1,3}$/.test(part) && Number(part) <= 255);
}
function isLoopbackHostname(hostname) {
	if (hostname === "localhost" || hostname === "[::1]") return true;
	return isIPv4Loopback(hostname);
}
/** Loopback trust fence: socket address AND Host header AND same-origin markers. */
function isLoopbackRequest(request) {
	const remote = request.socket.remoteAddress;
	if (remote === void 0) return false;
	const address = remote.toLowerCase();
	if (!(address === "::1" || address.startsWith("::ffff:") && isIPv4Loopback(address.slice(7)) || isIPv4Loopback(address))) return false;
	const host = request.headers.host;
	if (typeof host !== "string") return false;
	let hostUrl;
	try {
		hostUrl = new URL("http://" + host);
	} catch {
		return false;
	}
	if (!isLoopbackHostname(hostUrl.hostname)) return false;
	if (request.headers["sec-fetch-site"] === "cross-site") return false;
	const origin = request.headers.origin;
	if (origin === void 0) return true;
	try {
		return new URL(origin).host === hostUrl.host;
	} catch {
		return false;
	}
}
const JSON_HEADERS = {
	"content-type": "application/json; charset=utf-8",
	"referrer-policy": "no-referrer"
};
function writeJson(res, status, body) {
	res.writeHead(status, JSON_HEADERS);
	res.end(JSON.stringify(body));
}
/** Resolve $DSH_HOME with a ~/.dsh fallback. */
function dshHome(env = process.env, home = homedir()) {
	home.startsWith("/");
	const isAbs = isAbsolute;
	const raw = env.DSH_HOME;
	if (raw !== void 0 && raw.trim() !== "") {
		const expanded = raw.trim().startsWith("~") ? join(home, raw.trim().slice(1).replace(/^[\\/]/, "")) : raw.trim();
		return isAbs(expanded) ? expanded : join(process.cwd(), expanded);
	}
	return join(home, ".dsh");
}
/** Run a command, capturing exit code and stderr (30 s cap). */
async function runCommand(file, args) {
	try {
		await execFileAsync(file, args, {
			timeout: 3e4,
			windowsHide: true
		});
		return {
			code: 0,
			stderr: ""
		};
	} catch (error) {
		const code = typeof error === "object" && error !== null && "code" in error ? error.code : null;
		return {
			code: typeof code === "number" ? code : null,
			stderr: error instanceof Error ? error.message : String(error)
		};
	}
}
/** The dsh icon bundled with the package (assets/ next to lib/). */
let bundledIconPath;
let bundledPngPath;
if (import.meta.url.startsWith("file:")) {
	try {
		bundledIconPath = fileURLToPath(new URL("../assets/dsh.ico", import.meta.url));
	} catch {}
	try {
		bundledPngPath = fileURLToPath(new URL("../assets/dsh.png", import.meta.url));
	} catch {}
}
function resolveIconSource(configured) {
	if (configured !== void 0 && configured !== "" && existsSync(configured)) return configured;
	return bundledIconPath !== void 0 && existsSync(bundledIconPath) ? bundledIconPath : void 0;
}
function toLauncherPlatform(platform) {
	if (platform === "win32" || platform === "darwin" || platform === "linux") return platform;
	throw new Error(`unsupported platform: ${platform}`);
}
/** Desktop directory with the Windows OneDrive redirect fallback. */
function resolveDesktopDir(home, platform) {
	const desktop = join(home, "Desktop");
	if (platform === "win32" && !existsSync(desktop)) {
		const onedrive = join(home, "OneDrive", "Desktop");
		if (existsSync(onedrive)) return onedrive;
	}
	return desktop;
}
/** Best-effort dsh probe on PATH (never throws). */
async function probeDsh(platform, dshCommand) {
	if (isAbsolute(dshCommand) || dshCommand.includes("/") || dshCommand.includes("\\")) return existsSync(dshCommand);
	try {
		return (platform === "win32" ? await runCommand("where", [dshCommand]) : await runCommand("sh", [
			"-lc",
			"command -v -- \"$1\"",
			"desktop-quick-launcher",
			dshCommand
		])).code === 0;
	} catch {
		return false;
	}
}
/** Write the launcher script + place the desktop icon for the current platform. */
async function createDesktopShortcut(specSource) {
	const spec = specSource();
	const platform = toLauncherPlatform(process.platform);
	const home = homedir();
	const scriptsDir = join(dshHome(), "desktop-quick-launcher");
	await mkdir(scriptsDir, { recursive: true });
	const launcherPath = join(scriptsDir, scriptFileName(platform));
	await writeFile(launcherPath, "﻿" + renderLauncherScript(platform, spec), { mode: 493 });
	let iconIco;
	let iconPng;
	const iconSource = resolveIconSource(spec.iconPath);
	if (iconSource !== void 0) {
		iconIco = join(scriptsDir, "dsh.ico");
		await copyFile(iconSource, iconIco);
		if (/\.png$/i.test(iconSource)) {
			iconPng = join(scriptsDir, "dsh.png");
			await copyFile(iconSource, iconPng);
		} else if (bundledPngPath !== void 0 && existsSync(bundledPngPath)) {
			iconPng = join(scriptsDir, "dsh.png");
			await copyFile(bundledPngPath, iconPng);
		}
	}
	const desktopDir = resolveDesktopDir(home, platform);
	await mkdir(desktopDir, { recursive: true });
	const iconPath = join(desktopDir, desktopFileName(platform));
	let warning;
	if (!await probeDsh(platform, spec.dshCommand)) warning = `dsh command "${spec.dshCommand}" was not found on PATH; the launcher shows a message when run`;
	if (platform === "win32") {
		const installerPath = join(scriptsDir, "install-shortcut.ps1");
		await writeFile(installerPath, "﻿" + renderShortcutInstaller({
			launcherPath,
			desktopPath: iconPath,
			workingDirectory: scriptsDir,
			iconLocation: iconIco ?? "powershell.exe,0"
		}));
		const result = await runCommand("powershell", [
			"-NoProfile",
			"-ExecutionPolicy",
			"Bypass",
			"-File",
			installerPath
		]);
		if (result.code !== 0) throw new Error(`shortcut creation failed: ${result.stderr}`);
	} else if (platform === "darwin") await writeFile(iconPath, renderLauncherScript(platform, spec), { mode: 493 });
	else {
		await writeFile(iconPath, renderDesktopEntry(launcherPath, iconPng ?? iconIco), { mode: 493 });
		await chmod(launcherPath, 493);
		const trust = await runCommand("gio", [
			"set",
			iconPath,
			"metadata::trusted",
			"true"
		]);
		if (trust.code !== 0) warning = `desktop entry created but not marked trusted: ${trust.stderr}`;
	}
	return {
		ok: true,
		path: iconPath,
		platform,
		...warning === void 0 ? {} : { warning }
	};
}
/** How long the exit request waits after the response is flushed. */
const EXIT_DELAY_MS = 500;
/**
* Mount the routes, the shutdown surface, the settings section, and the
* (optional) system-prompt section.
* @param ctx - host plugin context carrying webServer/systemPrompt.
* @param config - resolved plugin config.
*/
function apply(ctx, config) {
	let current = () => config ?? {};
	let disposeRoutes;
	let disposeShutdown;
	let disposeSection;
	let exitRequested = false;
	const requestExit = (code) => {
		if (exitRequested) return;
		exitRequested = true;
		const exit = ctx.get("appExit");
		if (exit !== void 0) {
			exit(code);
			return;
		}
		process.exit(code);
	};
	const sync = () => {
		if (disposeSection !== void 0) {
			disposeSection();
			disposeSection = void 0;
		}
		if (disposeRoutes !== void 0) {
			disposeRoutes();
			disposeRoutes = void 0;
		}
		if (disposeShutdown !== void 0) {
			disposeShutdown();
			disposeShutdown = void 0;
		}
		const createRoute = {
			kind: "exact",
			path: LAUNCHER_API.create,
			handler: async (req, res) => {
				if (!isLoopbackRequest(req)) {
					writeJson(res, 403, { error: "forbidden: loopback-only" });
					return;
				}
				if ((req.method ?? "GET") !== "POST") {
					writeJson(res, 405, { error: `method not allowed: ${req.method}` });
					return;
				}
				try {
					writeJson(res, 200, { result: await createDesktopShortcut(() => resolveLauncherSpec(current())) });
				} catch (error) {
					writeJson(res, 500, { error: error instanceof Error ? error.message : String(error) });
				}
			}
		};
		const shutdownRoute = {
			kind: "exact",
			path: LAUNCHER_API.shutdown,
			handler: async (req, res) => {
				if (req.method !== "POST") {
					res.writeHead(405, { "content-type": "text/plain; charset=utf-8" });
					res.end("method not allowed");
					return;
				}
				if (!isLoopbackRequest(req)) {
					writeJson(res, 403, {
						ok: false,
						code: "forbidden"
					});
					return;
				}
				writeJson(res, 200, { ok: true });
				setTimeout(() => requestExit(0), EXIT_DELAY_MS);
			}
		};
		disposeRoutes = ctx.webServer.register(createRoute);
		disposeShutdown = ctx.webServer.register(shutdownRoute);
		const value = current();
		if ((value.enabled ?? true) !== false && (value.announceToAgent ?? false) !== false) disposeSection = ctx.systemPrompt.section({
			name: "plugin:desktop-quick-launcher",
			order: SECTION_ORDER,
			text: DESKTOP_QUICK_LAUNCHER_GUIDANCE
		});
	};
	ctx.inject(["settings"], (settingsCtx) => {
		settingsCtx.settings.installSection(ctx, NAMESPACE, Config, config ?? {}, {
			setSource: (source) => {
				current = source;
				sync();
			},
			onChange: sync
		});
	});
	sync();
}
//#endregion
export { Config, LAUNCHER_API, apply, createDesktopShortcut, inject, name, renderLauncherScript };
