/**
 * Pure launcher generation — migrated from @linxin666/dsh-desktop-launcher
 * (src/core/launcher.ts, Apache-2.0). Produces the PowerShell / POSIX launcher
 * bodies, the Windows shortcut installer, and the desktop file names for the
 * three supported platforms. No filesystem or process access: everything here
 * is testable without touching disk.
 *
 * Adaptations vs. the retired upstream:
 *  - The PowerShell body no longer renders the WPF startup popup (its
 *    `Start-Process $url` open step proved unreliable on some Windows hosts).
 *    The replacement polls with logging (launcher.log next to the script),
 *    opens the browser with two fallbacks, waits up to 120 s, and surfaces
 *    failures in a plain message box.
 */

/** Desktop platforms the launcher can generate an icon for. */
export type LauncherPlatform = 'win32' | 'darwin' | 'linux'

/** Launcher behavior, resolved from plugin config. */
export interface LauncherSpec {
  /** Command that starts dsh (must be on PATH when the launcher runs). */
  dshCommand: string
  /** Base URL of the dsh web GUI. */
  url: string
  /** Optional profile started as `dsh --profile <profile> --no-open`. */
  profile?: string
  /** Optional icon file (.ico/.png); empty uses the bundled dsh icon. */
  iconPath?: string
}

/** Default dsh command. */
export const DEFAULT_DSH_COMMAND = 'dsh'

/** Default GUI URL. */
export const DEFAULT_URL = 'http://127.0.0.1:3080'

/** Resolve defaults from a partial config; empty profile means "no --profile flag". */
export function resolveLauncherSpec(config: {
  dshCommand?: string
  url?: string
  profile?: string
  iconPath?: string
}): LauncherSpec {
  return {
    dshCommand: config.dshCommand ?? DEFAULT_DSH_COMMAND,
    url: config.url ?? DEFAULT_URL,
    ...(config.profile === undefined || config.profile === '' ? {} : { profile: config.profile }),
    ...(config.iconPath === undefined || config.iconPath === '' ? {} : { iconPath: config.iconPath }),
  }
}

/** File name of the launcher script under <dsh-home>/desktop-quick-launcher/. */
export function scriptFileName(platform: LauncherPlatform): string {
  switch (platform) {
    case 'win32': return 'launcher.ps1'
    case 'darwin': return 'launcher.command'
    case 'linux': return 'launcher.sh'
  }
}

/** File name of the icon placed on the Desktop. */
export function desktopFileName(platform: LauncherPlatform): string {
  switch (platform) {
    case 'win32': return 'DSH-Web.lnk'
    case 'darwin': return 'DeepSeek-Harness.command'
    case 'linux': return 'deepseek-harness.desktop'
  }
}

/** Single-quote a value for PowerShell (embedded quotes are doubled). */
function psSingle(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

/** Single-quote a value for POSIX sh (embedded quotes are escaped). */
function shSingle(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`
}

/**
 * PowerShell launcher body: probes the URL, starts `dsh web --no-open`
 * hidden, polls until the GUI answers (logging every step), then opens the
 * default browser. If dsh is missing or the 120 s budget runs out, a message
 * box explains what happened and where the log lives.
 */
function renderPowerShell(spec: LauncherSpec): string {
  return [
    '# DSH web launcher (generated by desktop-quick-launcher)',
    "$ErrorActionPreference = 'Continue'",
    `$dshCommand = ${psSingle(spec.dshCommand)}`,
    `$url = ${psSingle(spec.url)}`,
    `$profile = ${psSingle(spec.profile ?? '')}`,
    "$log = Join-Path $PSScriptRoot 'launcher.log'",
    '',
    'function Write-Log($message) {',
    '  try { Add-Content -Path $log -Value ((\"[{0}] {1}\" -f (Get-Date -Format \"s\"), $message)) } catch {}',
    '}',
    '',
    'function Test-DshUrl {',
    '  try {',
    '    $r = Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 2',
    '    return $r.StatusCode -ge 200 -and $r.StatusCode -lt 500',
    '  } catch {',
    '    if ($_.Exception.Response -and $_.Exception.Response.StatusCode) {',
    '      $code = [int]$_.Exception.Response.StatusCode',
    '      return $code -ge 200 -and $code -lt 500',
    '    }',
    '    return $false',
    '  }',
    '}',
    '',
    'function Open-Browser {',
    '  try { Start-Process -FilePath $url -ErrorAction Stop; return } catch { Write-Log \"Start-Process open failed: $_\" }',
    '  try { Start-Process -FilePath \"explorer.exe\" -ArgumentList $url -ErrorAction Stop } catch { Write-Log \"explorer open failed: $_\" }',
    '}',
    '',
    'function Show-Message($text, $title) {',
    '  try {',
    '    Add-Type -AssemblyName PresentationFramework -ErrorAction Stop | Out-Null',
    '    [System.Windows.MessageBox]::Show($text, $title) | Out-Null',
    '  } catch { Write-Log \"message box failed: $_\" }',
    '}',
    '',
    "Write-Log 'launcher invoked'",
    'if (Test-DshUrl) {',
    '  Write-Log \"already running -> open $url\"',
    '  Open-Browser',
    '  exit 0',
    '}',
    '',
    '$commands = @(Get-Command $dshCommand -All -ErrorAction SilentlyContinue)',
    "$command = $commands | Where-Object { $_.CommandType -eq 'Application' -and $_.Source -match '\\.(?:cmd|exe|bat|com)$' } | Select-Object -First 1",
    "if ($null -eq $command) { $command = $commands | Where-Object { $_.CommandType -eq 'Application' } | Select-Object -First 1 }",
    "if ($null -eq $command) { $command = $commands | Where-Object { $_.CommandType -eq 'ExternalScript' } | Select-Object -First 1 }",
    'if ($null -eq $command) {',
    '  Show-Message (\"找不到 dsh 命令：\" + $dshCommand) \"DSH Quick Launcher\"',
    '  exit 1',
    '}',
    '',
    "Write-Log (\"found dsh: \" + $command.Source)",
    '$arguments = if ($profile -eq "") { @("web", "--no-open") } else { @("--profile", $profile, "--no-open") }',
    'if ($command.CommandType -eq "ExternalScript" -or $command.Source -match "\\.ps1$") {',
    '  $arguments = @("-NoProfile", "-File", $command.Source) + $arguments',
    '  $dshProcess = Start-Process -FilePath "powershell.exe" -ArgumentList $arguments -WindowStyle Hidden -PassThru',
    '} else {',
    '  $dshProcess = Start-Process -FilePath $command.Source -ArgumentList $arguments -WindowStyle Hidden -PassThru',
    '}',
    '',
    '$deadline = (Get-Date).AddSeconds(120)',
    'while ((Get-Date) -lt $deadline) {',
    '  Start-Sleep -Milliseconds 500',
    '  if (Test-DshUrl) {',
    "    Write-Log 'service ready -> open browser'",
    '    Open-Browser',
    '    exit 0',
    '  }',
    '  if ($null -ne $dshProcess -and $dshProcess.HasExited) {',
    '    Show-Message (\"DSH 进程已退出（代码：\" + $dshProcess.ExitCode + \"） 日志：$log\") \"DSH Quick Launcher\"',
    '    exit 1',
    '  }',
    '}',
    'Show-Message (\"120 秒内未就绪：\" + $url + \"`n日志：$log\") \"DSH Quick Launcher\"',
    'exit 1',
    '',
  ].join('\n')
}

/** POSIX launcher (macOS .command / Linux .sh) with the platform open command. */
function renderPosix(platform: 'darwin' | 'linux', spec: LauncherSpec): string {
  const open = platform === 'darwin' ? 'open' : 'xdg-open'
  const alert = platform === 'darwin'
    ? "osascript -e 'display dialog \"dsh command not found: '\"$DASH\"'\" with title \"DSH Quick Launcher\" with icon caution' 2>/dev/null || echo \"dsh command not found: $DASH\" >&2"
    : 'zenity --error --title="DSH Quick Launcher" --text="dsh command not found: $DASH" 2>/dev/null || echo "dsh command not found: $DASH" >&2'
  return [
    '#!/bin/bash',
    '# DSH web launcher (generated by desktop-quick-launcher)',
    `DASH=${shSingle(spec.dshCommand)}`,
    `URL=${shSingle(spec.url)}`,
    `PROFILE=${shSingle(spec.profile ?? '')}`,
    '',
    'probe() {',
    '  curl -fsS --max-time 2 "$URL" >/dev/null 2>&1',
    '}',
    '',
    'if probe; then',
    `  ${open} "$URL"`,
    '  exit 0',
    'fi',
    '',
    'if ! command -v "$DASH" >/dev/null 2>&1; then',
    `  ${alert}`,
    '  exit 1',
    'fi',
    '',
    'if [ -n "$PROFILE" ]; then',
    '  "$DASH" --profile "$PROFILE" --no-open >/dev/null 2>&1 &',
    'else',
    '  "$DASH" web --no-open >/dev/null 2>&1 &',
    'fi',
    'DASH_PID=$!',
    '',
    'for i in $(seq 1 60); do',
    '  if probe; then',
    `    ${open} "$URL"`,
    '    exit 0',
    '  fi',
    '  if ! kill -0 "$DASH_PID" 2>/dev/null; then',
    '    echo "dsh process exited unexpectedly" >&2',
    '    exit 1',
    '  fi',
    '  sleep 2',
    'done',
    '',
    'echo "dsh web did not start within 120 seconds: $URL" >&2',
    'exit 1',
    '',
  ].join('\n')
}

/** Render the launcher script for one platform. */
export function renderLauncherScript(platform: LauncherPlatform, spec: LauncherSpec): string {
  switch (platform) {
    case 'win32': return renderPowerShell(spec)
    case 'darwin':
    case 'linux': return renderPosix(platform, spec)
  }
}

/** Render the Linux desktop entry (macOS uses the launcher itself as the desktop file). */
export function renderDesktopEntry(launcherPath: string, iconPath?: string): string {
  const iconLine = iconPath === undefined ? 'Icon=utilities-terminal' : `Icon=${iconPath}`
  return [
    '[Desktop Entry]',
    'Type=Application',
    'Version=1.0',
    'Name=DSH Web',
    'Comment=Launch DeepSeek Harness Web GUI',
    `Exec="${launcherPath}"`,
    iconLine,
    'Terminal=true',
    'Categories=Development;',
    '',
  ].join('\n')
}

/**
 * Render the Windows shortcut installer: a PowerShell script that creates the
 * Desktop .lnk pointing at the launcher script, executed hidden by the host.
 */
export function renderShortcutInstaller(opts: {
  /** Absolute path of launcher.ps1. */
  launcherPath: string
  /** Absolute path of the .lnk to create. */
  desktopPath: string
  /** Working directory of the shortcut. */
  workingDirectory?: string
  /** Icon the shortcut shows (an .ico/.png path, or a shell-exe icon spec). */
  iconLocation: string
}): string {
  const { launcherPath, desktopPath, workingDirectory, iconLocation } = opts
  const targetWorkingDir = workingDirectory ?? ''
  return [
    '# DSH desktop shortcut installer (generated by desktop-quick-launcher)',
    "$ErrorActionPreference = 'Stop'",
    '$ws = New-Object -ComObject WScript.Shell',
    `$shortcut = $ws.CreateShortcut(${psSingle(desktopPath)})`,
    `$shortcut.TargetPath = ${psSingle('powershell.exe')}`,
    `$shortcut.Arguments = ${psSingle(`-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ${launcherPath}`)}`,
    `$shortcut.WorkingDirectory = ${psSingle(targetWorkingDir)}`,
    `$shortcut.IconLocation = ${psSingle(iconLocation)}`,
    `$shortcut.Description = ${psSingle('Launch DeepSeek Harness Web GUI')}`,
    '$shortcut.Save()',
    '',
  ].join('\n')
}
